
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class CountryPickerLocalizations {
  final Locale locale;
  const CountryPickerLocalizations(this.locale);

  static CountryPickerLocalizations of(BuildContext context) {
    return Localizations.of<CountryPickerLocalizations>(
      context,
      CountryPickerLocalizations,
    ) ??
        const CountryPickerLocalizations(Locale('en'));
  }

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('hi'),
    Locale('es'),
    Locale('fr'),
    Locale('de'),
  ];

  String get sheetTitle => _stringsFor(locale)['sheetTitle']!;
  String get searchHint => _stringsFor(locale)['searchHint']!;
  String get noResults => _stringsFor(locale)['noResults']!;

  String countryName(String isoCode, String fallback) {
    final iso = isoCode.toUpperCase();
    final map = _countryNamesFor(locale);
    return map[iso] ?? fallback;
  }

  Map<String, String> _stringsFor(Locale locale) {
    switch (locale.languageCode) {
      case 'hi':
        return const {
          'sheetTitle': 'देश चुनें',
          'searchHint': 'देश, ISO, या कोड खोजें',
          'noResults': 'कोई परिणाम नहीं',
        };
      case 'de':
        return const {
          'sheetTitle': 'Land auswählen',
          'searchHint': 'Suche nach Land, ISO oder Code',
          'noResults': 'Keine Ergebnisse',
        };
      case 'es':
        return const {
          'sheetTitle': 'Seleccionar país',
          'searchHint': 'Buscar país, ISO o código',
          'noResults': 'Sin resultados',
        };
      case 'fr':
        return const {
          'sheetTitle': 'Sélectionner un pays',
          'searchHint': 'Rechercher pays, ISO ou code',
          'noResults': 'Aucun résultat',
        };
      case 'en':
      default:
        return const {
          'sheetTitle': 'Select country',
          'searchHint': 'Search by name, ISO, or code',
          'noResults': 'No results',
        };
    }
  }

  Map<String, String> _countryNamesFor(Locale locale) {
    switch (locale.languageCode) {
      case 'hi':
        return const {
          'AF': 'अफ़ग़ानिस्तान',
          'AL': 'अल्बानिया',
          'DZ': 'अल्जीरिया',
          'AS': 'अमेरिकी समोआ',
          'AD': 'अंडोरा',
          'AO': 'अंगोला',
          'AI': 'एंग्विला',
          'AQ': 'अंटार्कटिका',
          'AG': 'एंटिगुआ और बारबुडा',
          'AR': 'अर्जेंटीना',
          'AM': 'आर्मेनिया',
          'AW': 'अरूबा',
          'AU': 'ऑस्ट्रेलिया',
          'AT': 'ऑस्ट्रिया',
          'AZ': 'अज़रबैजान',
          'BS': 'बहामास',
          'BH': 'बहरीन',
          'BD': 'बांग्लादेश',
          'BB': 'बारबाडोस',
          'BY': 'बेलारूस',
          'BE': 'बेल्जियम',
          'BZ': 'बेलीज़',
          'BJ': 'बेनिन',
          'BM': 'बरमूडा',
          'BT': 'भूटान',
          'BO': 'बोलीविया',
          'BA': 'बोस्निया और हर्जेगोविना',
          'BW': 'बोत्सवाना',
          'BR': 'ब्राज़ील',
          'IO': 'ब्रिटिश हिंद महासागर क्षेत्र',
          'BN': 'ब्रुनेई',
          'BG': 'बुल्गारिया',
          'BF': 'बुर्किना फासो',
          'BI': 'बुरुंडी',
          'KH': 'कंबोडिया',
          'CM': 'कैमरून',
          'CA': 'कनाडा',
          'CV': 'केप वर्डे',
          'KY': 'केमैन द्वीपसमूह',
          'CF': 'मध्य अफ्रीकी गणराज्य',
          'TD': 'चाड',
          'CL': 'चिली',
          'CN': 'चीन',
          'CO': 'कोलम्बिया',
          'KM': 'कोमोरोस',
          'CG': 'कांगो',
          'CD': 'कांगो लोकतांत्रिक गणराज्य',
          'CR': 'कोस्टा रिका',
          'HR': 'क्रोएशिया',
          'CU': 'क्यूबा',
          'CY': 'साइप्रस',
          'CZ': 'चेक गणराज्य',
          'DK': 'डेनमार्क',
          'DJ': 'जिबूती',
          'DM': 'डोमिनिका',
          'DO': 'डोमिनिकन गणराज्य',
          'EC': 'इक्वाडोर',
          'EG': 'मिस्र',
          'SV': 'अल साल्वाडोर',
          'GQ': 'इक्वेटोरियल गिनी',
          'ER': 'इरिट्रिया',
          'EE': 'एस्टोनिया',
          'ET': 'इथियोपिया',
          'FJ': 'फिजी',
          'FI': 'फिनलैंड',
          'FR': 'फ्रांस',
          'GA': 'गैबॉन',
          'GM': 'गाम्बिया',
          'GE': 'जॉर्जिया',
          'DE': 'जर्मनी',
          'GH': 'घाना',
          'GR': 'ग्रीस',
          'GD': 'ग्रेनेडा',
          'GT': 'ग्वाटेमाला',
          'GN': 'गिनी',
          'GW': 'गिनी-बिसाऊ',
          'GY': 'गुयाना',
          'HT': 'हैती',
          'HN': 'होंडुरास',
          'HK': 'हांगकांग',
          'HU': 'हंगरी',
          'IS': 'आइसलैंड',
          'IN': 'भारत',
          'ID': 'इंडोनेशिया',
          'IR': 'ईरान',
          'IQ': 'इराक',
          'IE': 'आयरलैंड',
          'IL': 'इज़राइल',
          'IT': 'इटली',
          'JM': 'जमैका',
          'JP': 'जापान',
          'JO': 'जॉर्डन',
          'KZ': 'कज़ाख़िस्तान',
          'KE': 'केन्या',
          'KR': 'दक्षिण कोरिया',
          'KP': 'उत्तर कोरिया',
          'KW': 'कुवैत',
          'KG': 'किर्गिज़स्तान',
          'LA': 'लाओस',
          'LV': 'लातविया',
          'LB': 'लेबनान',
          'LS': 'लेसोथो',
          'LR': 'लाइबेरिया',
          'LY': 'लीबिया',
          'LT': 'लिथुआनिया',
          'LU': 'लक्ज़मबर्ग',
          'MG': 'मेडागास्कर',
          'MW': 'मलावी',
          'MY': 'मलेशिया',
          'MV': 'मालदीव',
          'ML': 'माली',
          'MT': 'माल्टा',
          'MX': 'मेक्सिको',
          'MD': 'मोल्दोवा',
          'MC': 'मोनाको',
          'MN': 'मंगोलिया',
          'MA': 'मोरक्को',
          'MZ': 'मोज़ाम्बिक',
          'MM': 'म्यांमार',
          'NA': 'नामीबिया',
          'NP': 'नेपाल',
          'NL': 'नीदरलैंड',
          'NZ': 'न्यूज़ीलैंड',
          'NI': 'निकारागुआ',
          'NE': 'नाइजर',
          'NG': 'नाइजीरिया',
          'NO': 'नॉर्वे',
          'OM': 'ओमान',
          'PK': 'पाकिस्तान',
          'PA': 'पनामा',
          'PG': 'पापुआ न्यू गिनी',
          'PY': 'पैराग्वे',
          'PE': 'पेरू',
          'PH': 'फिलीपींस',
          'PL': 'पोलैंड',
          'PT': 'पुर्तगाल',
          'PR': 'प्यूर्टो रिको',
          'QA': 'क़तर',
          'RO': 'रोमानिया',
          'RU': 'रूस',
          'RW': 'रवांडा',
          'SA': 'सऊदी अरब',
          'SN': 'सेनेगल',
          'RS': 'सर्बिया',
          'SG': 'सिंगापुर',
          'SK': 'स्लोवाकिया',
          'SI': 'स्लोवेनिया',
          'ZA': 'दक्षिण अफ्रीका',
          'ES': 'स्पेन',
          'LK': 'श्रीलंका',
          'SD': 'सूडान',
          'SE': 'स्वीडन',
          'CH': 'स्विट्जरलैंड',
          'SY': 'सीरिया',
          'TW': 'ताइवान',
          'TJ': 'ताजिकिस्तान',
          'TZ': 'तंज़ानिया',
          'TH': 'थाईलैंड',
          'TR': 'तुर्की',
          'TN': 'ट्यूनीशिया',
          'UG': 'युगांडा',
          'UA': 'यूक्रेन',
          'AE': 'संयुक्त अरब अमीरात',
          'GB': 'यूनाइटेड किंगडम',
          'US': 'संयुक्त राज्य',
          'UY': 'उरुग्वे',
          'UZ': 'उज़्बेकिस्तान',
          'VE': 'वेनेज़ुएला',
          'VN': 'वियतनाम',
          'YE': 'यमन',
          'ZM': 'ज़ाम्बिया',
          'ZW': 'ज़िम्बाब्वे',
        };
      case 'de':
        return const {
          'AF': 'Afghanistan',
          'AL': 'Albanien',
          'DZ': 'Algerien',
          'AS': 'Amerikanisch-Samoa',
          'AD': 'Andorra',
          'AO': 'Angola',
          'AI': 'Anguilla',
          'AQ': 'Antarktis',
          'AG': 'Antigua und Barbuda',
          'AR': 'Argentinien',
          'AM': 'Armenien',
          'AW': 'Aruba',
          'AU': 'Australien',
          'AT': 'Österreich',
          'AZ': 'Aserbaidschan',
          'BS': 'Bahamas',
          'BH': 'Bahrain',
          'BD': 'Bangladesch',
          'BB': 'Barbados',
          'BY': 'Weißrussland',
          'BE': 'Belgien',
          'BZ': 'Belize',
          'BJ': 'Benin',
          'BM': 'Bermuda',
          'BT': 'Bhutan',
          'BO': 'Bolivien',
          'BA': 'Bosnien und Herzegowina',
          'BW': 'Botsuana',
          'BR': 'Brasilien',
          'IO': 'Britisches Territorium im Indischen Ozean',
          'BN': 'Brunei',
          'BG': 'Bulgarien',
          'BF': 'Burkina Faso',
          'BI': 'Burundi',
          'KH': 'Kambodscha',
          'CM': 'Kamerun',
          'CA': 'Kanada',
          'CV': 'Kap Verde',
          'KY': 'Kaimaninseln',
          'CF': 'Zentralafrikanische Republik',
          'TD': 'Tschad',
          'CL': 'Chile',
          'CN': 'China',
          'CO': 'Kolumbien',
          'KM': 'Komoren',
          'CG': 'Kongo',
          'CD': 'Demokratische Republik Kongo',
          'CR': 'Costa Rica',
          'HR': 'Kroatien',
          'CU': 'Kuba',
          'CY': 'Zypern',
          'CZ': 'Tschechien',
          'DK': 'Dänemark',
          'DJ': 'Dschibuti',
          'DM': 'Dominica',
          'DO': 'Dominikanische Republik',
          'EC': 'Ecuador',
          'EG': 'Ägypten',
          'SV': 'El Salvador',
          'GQ': 'Äquatorialguinea',
          'ER': 'Eritrea',
          'EE': 'Estland',
          'ET': 'Äthiopien',
          'FJ': 'Fidschi',
          'FI': 'Finnland',
          'FR': 'Frankreich',
          'GA': 'Gabun',
          'GM': 'Gambia',
          'GE': 'Georgien',
          'DE': 'Deutschland',
          'GH': 'Ghana',
          'GR': 'Griechenland',
          'GD': 'Grenada',
          'GT': 'Guatemala',
          'GN': 'Guinea',
          'GW': 'Guinea-Bissau',
          'GY': 'Guyana',
          'HT': 'Haiti',
          'HN': 'Honduras',
          'HK': 'Hongkong',
          'HU': 'Ungarn',
          'IS': 'Island',
          'IN': 'Indien',
          'ID': 'Indonesien',
          'IR': 'Iran',
          'IQ': 'Irak',
          'IE': 'Irland',
          'IL': 'Israel',
          'IT': 'Italien',
          'JM': 'Jamaika',
          'JP': 'Japan',
          'JO': 'Jordanien',
          'KZ': 'Kasachstan',
          'KE': 'Kenia',
          'KR': 'Südkorea',
          'KP': 'Nordkorea',
          'KW': 'Kuwait',
          'KG': 'Kirgisistan',
          'LA': 'Laos',
          'LV': 'Lettland',
          'LB': 'Libanon',
          'LS': 'Lesotho',
          'LR': 'Liberia',
          'LY': 'Libyen',
          'LT': 'Litauen',
          'LU': 'Luxemburg',
          'MG': 'Madagaskar',
          'MW': 'Malawi',
          'MY': 'Malaysia',
          'MV': 'Malediven',
          'ML': 'Mali',
          'MT': 'Malta',
          'MX': 'Mexiko',
          'MD': 'Moldawien',
          'MC': 'Monaco',
          'MN': 'Mongolei',
          'MA': 'Marokko',
          'MZ': 'Mosambik',
          'MM': 'Myanmar',
          'NA': 'Namibia',
          'NP': 'Nepal',
          'NL': 'Niederlande',
          'NZ': 'Neuseeland',
          'NI': 'Nicaragua',
          'NE': 'Niger',
          'NG': 'Nigeria',
          'NO': 'Norwegen',
          'OM': 'Oman',
          'PK': 'Pakistan',
          'PA': 'Panama',
          'PG': 'Papua-Neuguinea',
          'PY': 'Paraguay',
          'PE': 'Peru',
          'PH': 'Philippinen',
          'PL': 'Polen',
          'PT': 'Portugal',
          'PR': 'Puerto Rico',
          'QA': 'Katar',
          'RO': 'Rumänien',
          'RU': 'Russland',
          'RW': 'Ruanda',
          'SA': 'Saudi-Arabien',
          'SN': 'Senegal',
          'RS': 'Serbien',
          'SG': 'Singapur',
          'SK': 'Slowakei',
          'SI': 'Slowenien',
          'ZA': 'Südafrika',
          'ES': 'Spanien',
          'LK': 'Sri Lanka',
          'SD': 'Sudan',
          'SE': 'Schweden',
          'CH': 'Schweiz',
          'SY': 'Syrien',
          'TW': 'Taiwan',
          'TJ': 'Tadschikistan',
          'TZ': 'Tansania',
          'TH': 'Thailand',
          'TR': 'Türkei',
          'TN': 'Tunesien',
          'UG': 'Uganda',
          'UA': 'Ukraine',
          'AE': 'Vereinigte Arabische Emirate',
          'GB': 'Vereinigtes Königreich',
          'US': 'Vereinigte Staaten',
          'UY': 'Uruguay',
          'UZ': 'Usbekistan',
          'VE': 'Venezuela',
          'VN': 'Vietnam',
          'YE': 'Jemen',
          'ZM': 'Sambia',
          'ZW': 'Simbabwe',
        };
      case 'es':
        return const {
          'AF': 'Afganistán',
          'AL': 'Albania',
          'DZ': 'Argelia',
          'AS': 'Samoa Americana',
          'AD': 'Andorra',
          'AO': 'Angola',
          'AI': 'Anguila',
          'AQ': 'Antártida',
          'AG': 'Antigua y Barbuda',
          'AR': 'Argentina',
          'AM': 'Armenia',
          'AW': 'Aruba',
          'AU': 'Australia',
          'AT': 'Austria',
          'AZ': 'Azerbaiyán',
          'BS': 'Bahamas',
          'BH': 'Baréin',
          'BD': 'Bangladés',
          'BB': 'Barbados',
          'BY': 'Bielorrusia',
          'BE': 'Bélgica',
          'BZ': 'Belice',
          'BJ': 'Benín',
          'BM': 'Bermudas',
          'BT': 'Bután',
          'BO': 'Bolivia',
          'BA': 'Bosnia y Herzegovina',
          'BW': 'Botsuana',
          'BR': 'Brasil',
          'IO': 'Territorio Británico del Océano Índico',
          'BN': 'Brunéi',
          'BG': 'Bulgaria',
          'BF': 'Burkina Faso',
          'BI': 'Burundi',
          'KH': 'Camboya',
          'CM': 'Camerún',
          'CA': 'Canadá',
          'CV': 'Cabo Verde',
          'KY': 'Islas Caimán',
          'CF': 'República Centroafricana',
          'TD': 'Chad',
          'CL': 'Chile',
          'CN': 'China',
          'CO': 'Colombia',
          'KM': 'Comoras',
          'CG': 'Congo',
          'CD': 'República Democrática del Congo',
          'CR': 'Costa Rica',
          'HR': 'Croacia',
          'CU': 'Cuba',
          'CY': 'Chipre',
          'CZ': 'Chequia',
          'DK': 'Dinamarca',
          'DJ': 'Yibuti',
          'DM': 'Dominica',
          'DO': 'República Dominicana',
          'EC': 'Ecuador',
          'EG': 'Egipto',
          'SV': 'El Salvador',
          'GQ': 'Guinea Ecuatorial',
          'ER': 'Eritrea',
          'EE': 'Estonia',
          'ET': 'Etiopía',
          'FJ': 'Fiyi',
          'FI': 'Finlandia',
          'FR': 'Francia',
          'GA': 'Gabón',
          'GM': 'Gambia',
          'GE': 'Georgia',
          'DE': 'Alemania',
          'GH': 'Ghana',
          'GR': 'Grecia',
          'GD': 'Granada',
          'GT': 'Guatemala',
          'GN': 'Guinea',
          'GW': 'Guinea-Bisáu',
          'GY': 'Guyana',
          'HT': 'Haití',
          'HN': 'Honduras',
          'HK': 'Hong Kong',
          'HU': 'Hungría',
          'IS': 'Islandia',
          'IN': 'India',
          'ID': 'Indonesia',
          'IR': 'Irán',
          'IQ': 'Irak',
          'IE': 'Irlanda',
          'IL': 'Israel',
          'IT': 'Italia',
          'JM': 'Jamaica',
          'JP': 'Japón',
          'JO': 'Jordania',
          'KZ': 'Kazajistán',
          'KE': 'Kenia',
          'KR': 'Corea del Sur',
          'KP': 'Corea del Norte',
          'KW': 'Kuwait',
          'KG': 'Kirguistán',
          'LA': 'Laos',
          'LV': 'Letonia',
          'LB': 'Líbano',
          'LS': 'Lesoto',
          'LR': 'Liberia',
          'LY': 'Libia',
          'LT': 'Lituania',
          'LU': 'Luxemburgo',
          'MG': 'Madagascar',
          'MW': 'Malaui',
          'MY': 'Malasia',
          'MV': 'Maldivas',
          'ML': 'Mali',
          'MT': 'Malta',
          'MX': 'México',
          'MD': 'Moldavia',
          'MC': 'Mónaco',
          'MN': 'Mongolia',
          'MA': 'Marruecos',
          'MZ': 'Mozambique',
          'MM': 'Birmania',
          'NA': 'Namibia',
          'NP': 'Nepal',
          'NL': 'Países Bajos',
          'NZ': 'Nueva Zelanda',
          'NI': 'Nicaragua',
          'NE': 'Níger',
          'NG': 'Nigeria',
          'NO': 'Noruega',
          'OM': 'Omán',
          'PK': 'Pakistán',
          'PA': 'Panamá',
          'PG': 'Papúa Nueva Guinea',
          'PY': 'Paraguay',
          'PE': 'Perú',
          'PH': 'Filipinas',
          'PL': 'Polonia',
          'PT': 'Portugal',
          'PR': 'Puerto Rico',
          'QA': 'Catar',
          'RO': 'Rumanía',
          'RU': 'Rusia',
          'RW': 'Ruanda',
          'SA': 'Arabia Saudita',
          'SN': 'Senegal',
          'RS': 'Serbia',
          'SG': 'Singapur',
          'SK': 'Eslovaquia',
          'SI': 'Eslovenia',
          'ZA': 'Sudáfrica',
          'ES': 'España',
          'LK': 'Sri Lanka',
          'SD': 'Sudán',
          'SE': 'Suecia',
          'CH': 'Suiza',
          'SY': 'Siria',
          'TW': 'Taiwán',
          'TJ': 'Tayikistán',
          'TZ': 'Tanzania',
          'TH': 'Tailandia',
          'TR': 'Turquía',
          'TN': 'Túnez',
          'UG': 'Uganda',
          'UA': 'Ucrania',
          'AE': 'Emiratos Árabes Unidos',
          'GB': 'Reino Unido',
          'US': 'Estados Unidos',
          'UY': 'Uruguay',
          'UZ': 'Uzbekistán',
          'VE': 'Venezuela',
          'VN': 'Vietnam',
          'YE': 'Yemen',
          'ZM': 'Zambia',
          'ZW': 'Zimbabue',
        };
      case 'fr':
        return const {
          'AF': 'Afghanistan',
          'AL': 'Albanie',
          'DZ': 'Algérie',
          'AS': 'Samoa américaines',
          'AD': 'Andorre',
          'AO': 'Angola',
          'AI': 'Anguilla',
          'AQ': 'Antarctique',
          'AG': 'Antigua-et-Barbuda',
          'AR': 'Argentine',
          'AM': 'Arménie',
          'AW': 'Aruba',
          'AU': 'Australie',
          'AT': 'Autriche',
          'AZ': 'Azerbaïdjan',
          'BS': 'Bahamas',
          'BH': 'Bahreïn',
          'BD': 'Bangladesh',
          'BB': 'Barbade',
          'BY': 'Biélorussie',
          'BE': 'Belgique',
          'BZ': 'Belize',
          'BJ': 'Bénin',
          'BM': 'Bermudes',
          'BT': 'Bhoutan',
          'BO': 'Bolivie',
          'BA': 'Bosnie-Herzégovine',
          'BW': 'Botswana',
          'BR': 'Brésil',
          'IO': 'Territoire britannique de l’océan Indien',
          'BN': 'Brunéi Darussalam',
          'BG': 'Bulgarie',
          'BF': 'Burkina Faso',
          'BI': 'Burundi',
          'KH': 'Cambodge',
          'CM': 'Cameroun',
          'CA': 'Canada',
          'CV': 'Cap-Vert',
          'KY': 'Îles Caïmans',
          'CF': 'République centrafricaine',
          'TD': 'Tchad',
          'CL': 'Chili',
          'CN': 'Chine',
          'CO': 'Colombie',
          'KM': 'Comores',
          'CG': 'Congo',
          'CD': 'République démocratique du Congo',
          'CR': 'Costa Rica',
          'HR': 'Croatie',
          'CU': 'Cuba',
          'CY': 'Chypre',
          'CZ': 'Tchéquie',
          'DK': 'Danemark',
          'DJ': 'Djibouti',
          'DM': 'Dominique',
          'DO': 'République dominicaine',
          'EC': 'Équateur',
          'EG': 'Égypte',
          'SV': 'Salvador',
          'GQ': 'Guinée équatoriale',
          'ER': 'Érythrée',
          'EE': 'Estonie',
          'ET': 'Éthiopie',
          'FJ': 'Fidji',
          'FI': 'Finlande',
          'FR': 'France',
          'GA': 'Gabon',
          'GM': 'Gambie',
          'GE': 'Géorgie',
          'DE': 'Allemagne',
          'GH': 'Ghana',
          'GR': 'Grèce',
          'GD': 'Grenade',
          'GT': 'Guatemala',
          'GN': 'Guinée',
          'GW': 'Guinée-Bissau',
          'GY': 'Guyana',
          'HT': 'Haïti',
          'HN': 'Honduras',
          'HK': 'Hong Kong',
          'HU': 'Hongrie',
          'IS': 'Islande',
          'IN': 'Inde',
          'ID': 'Indonésie',
          'IR': 'Iran',
          'IQ': 'Irak',
          'IE': 'Irlande',
          'IL': 'Israël',
          'IT': 'Italie',
          'JM': 'Jamaïque',
          'JP': 'Japon',
          'JO': 'Jordanie',
          'KZ': 'Kazakhstan',
          'KE': 'Kenya',
          'KR': 'Corée du Sud',
          'KP': 'Corée du Nord',
          'KW': 'Koweït',
          'KG': 'Kirghizistan',
          'LA': 'Laos',
          'LV': 'Lettonie',
          'LB': 'Liban',
          'LS': 'Lesotho',
          'LR': 'Libéria',
          'LY': 'Libye',
          'LT': 'Lituanie',
          'LU': 'Luxembourg',
          'MG': 'Madagascar',
          'MW': 'Malawi',
          'MY': 'Malaisie',
          'MV': 'Maldives',
          'ML': 'Mali',
          'MT': 'Malte',
          'MX': 'Mexique',
          'MD': 'Moldavie',
          'MC': 'Monaco',
          'MN': 'Mongolie',
          'MA': 'Maroc',
          'MZ': 'Mozambique',
          'MM': 'Birmanie',
          'NA': 'Namibie',
          'NP': 'Népal',
          'NL': 'Pays-Bas',
          'NZ': 'Nouvelle-Zélande',
          'NI': 'Nicaragua',
          'NE': 'Niger',
          'NG': 'Nigéria',
          'NO': 'Norvège',
          'OM': 'Oman',
          'PK': 'Pakistan',
          'PA': 'Panama',
          'PG': 'Papouasie-Nouvelle-Guinée',
          'PY': 'Paraguay',
          'PE': 'Pérou',
          'PH': 'Philippines',
          'PL': 'Pologne',
          'PT': 'Portugal',
          'PR': 'Porto Rico',
          'QA': 'Qatar',
          'RO': 'Roumanie',
          'RU': 'Russie',
          'RW': 'Rwanda',
          'SA': 'Arabie saoudite',
          'SN': 'Sénégal',
          'RS': 'Serbie',
          'SG': 'Singapour',
          'SK': 'Slovaquie',
          'SI': 'Slovénie',
          'ZA': 'Afrique du Sud',
          'ES': 'Espagne',
          'LK': 'Sri Lanka',
          'SD': 'Soudan',
          'SE': 'Suède',
          'CH': 'Suisse',
          'SY': 'Syrie',
          'TW': 'Taïwan',
          'TJ': 'Tadjikistan',
          'TZ': 'Tanzanie',
          'TH': 'Thaïlande',
          'TR': 'Turquie',
          'TN': 'Tunisie',
          'UG': 'Ouganda',
          'UA': 'Ukraine',
          'AE': 'Émirats arabes unis',
          'GB': 'Royaume-Uni',
          'US': 'États-Unis',
          'UY': 'Uruguay',
          'UZ': 'Ouzbékistan',
          'VE': 'Venezuela',
          'VN': 'Viêt Nam',
          'YE': 'Yémen',
          'ZM': 'Zambie',
          'ZW': 'Zimbabwe',
        };
      case 'en':
      default:
        return const {};
    }
  }
}

class CountryPickerLocalizationsDelegate
    extends LocalizationsDelegate<CountryPickerLocalizations> {
  const CountryPickerLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      CountryPickerLocalizations.supportedLocales
          .map((e) => e.languageCode)
          .contains(locale.languageCode);

  @override
  Future<CountryPickerLocalizations> load(Locale locale) {
    return SynchronousFuture(CountryPickerLocalizations(locale));
  }

  @override
  bool shouldReload(
      covariant LocalizationsDelegate<CountryPickerLocalizations> old) =>
      false;
}
